namespace MapTo.Sources
{
    internal class Constants
    {
        internal const string RootNamespace = "MapTo";
        internal const string GeneratedFilesHeader = "// <auto-generated />";
    }
}