using MapTo.Generators;

namespace MapTo.Tests.SourceBuilders;

internal record TestEmptyFileBuilder(string Name, string Content) : ITestFileBuilder
{
    /// <inheritdoc />
    public bool AutoGenerated => false;

    /// <inheritdoc />
    public IReadOnlyCollection<ICodeBuilder> Members => Array.Empty<ICodeBuilder>();

    /// <inheritdoc />
    public void AddMember(ICodeBuilder member) => throw new NotImplementedException();

    /// <inheritdoc />
    public void Build(CodeWriter writer, TestSourceBuilderOptions options)
    {
        writer.WriteLines(Content.Split(writer.NewLine));
    }
}

internal static class TestEmptyFileBuilderExtensions
{
    public static ITestSourceBuilder AddExternalFile(this ITestSourceBuilder builder, string filePath)
    {
        var sourceBuilder = (TestSourceBuilder)builder;
        sourceBuilder.AddFile(new TestEmptyFileBuilder(
            Path.GetFileName(filePath),
            File.ReadAllText(filePath)));

        return sourceBuilder;
    }
}