namespace MapTo.Tests;

internal static class ScenarioBuilder
{
    internal const string TestDataRelativeFolder = @"..\..\..\TestData";
    internal static readonly string GeneratedCodeAttribute =
        $$"""[global::System.CodeDom.Compiler.GeneratedCodeAttribute("MapTo", "{{typeof(MapToGenerator).Assembly.GetName().Version}}")]""";

    private const string AllowNull = "global::System.Diagnostics.CodeAnalysis.AllowNull";
    private const string ExpectedFileName = "ExpectedGeneratedFile";
    private const string NotNullIfNotNull = "global::System.Diagnostics.CodeAnalysis.NotNullIfNotNull";

    public static string GetExpectedFileContent(this ITestSourceBuilder builder) =>
        builder.GetGeneratedFile().Source;

    public static TestSource GetGeneratedFile(this ITestSourceBuilder builder) =>
        builder.Sources.GetSource(ExpectedFileName);

    public static ITestSourceBuilder SimpleMappedClassInDifferentNamespaceAsSource(TestSourceBuilderOptions? options = null)
    {
        var builder = new TestSourceBuilder(options ?? TestSourceBuilderOptions.Create());

        var sourceFile1 = builder.AddFile(ns: "ExternalLib", usings: new[] { "MapTo" });
        sourceFile1.AddClass(AccessModifier.Public, "SourceClass").WithProperty<int>("Id").WithProperty<string>("Name");

        var sourceFile2 = builder.AddFile(ns: "ExternalLibMap", usings: new[] { "MapTo", "ExternalLib" });
        sourceFile2.AddClass(AccessModifier.Public, "TargetClass", attributes: "[MapFrom(typeof(SourceClass))]")
            .WithProperty<int>("Id")
            .WithProperty<string>("Name");

        return builder;
    }

    public static ITestSourceBuilder SimplePartialMappedClassInSameNamespaceAsSource(TestSourceBuilderOptions? options = null)
    {
        var builder = new TestSourceBuilder(options ?? TestSourceBuilderOptions.Create());
        var sourceFile = builder.AddFile();
        sourceFile.AddClass(AccessModifier.Public, "SourceClass").WithProperty<int>("Id").WithProperty<string>("Name");
        sourceFile.AddClass(AccessModifier.Public, "TargetClass", partial: true, attributes: "[MapFrom(typeof(SourceClass))]")
            .WithProperty<int?>("Id", propertyType: PropertyType.ReadOnly | PropertyType.AutoProperty)
            .WithProperty<string>("Name");

        return builder;
    }

    public static ITestSourceBuilder SimpleMappedClassInSameNamespaceAsSource(TestSourceBuilderOptions? options = null)
    {
        var builder = new TestSourceBuilder(options ?? TestSourceBuilderOptions.Create());
        var sourceFile = builder.AddFile();
        sourceFile.AddClass(AccessModifier.Public, "SourceClass").WithProperty<int>("Id").WithProperty<string>("Name");
        sourceFile.AddClass(AccessModifier.Public, "TargetClass", attributes: "[MapFrom(typeof(SourceClass))]").WithProperty<int>("Id").WithProperty<string>("Name");

        var generatedFile = builder.AddFile(ExpectedFileName, autoGenerated: true);
        generatedFile.AddClass(SimpleExpectedExtensionClassThatMapsIdAndNameProperties(builder));

        return builder;
    }

    public static ITestSourceBuilder SimpleMappedClassInSameNamespaceAsSource(LanguageVersion version) =>
        SimpleMappedClassInSameNamespaceAsSource(TestSourceBuilderOptions.Create(version));

    public static ITestSourceBuilder SimpleMappedClassInSameNamespaceAsSourceWithInitProperty(LanguageVersion version = LanguageVersion.CSharp10)
    {
        var builder = new TestSourceBuilder(TestSourceBuilderOptions.Create(version));
        var sourceFile = builder.AddFile();
        sourceFile.AddClass(AccessModifier.Public, "SourceClass").WithProperty<int>("Id").WithProperty<string>("Name");
        sourceFile.AddClass(AccessModifier.Public, "TargetClass", attributes: "[MapFrom(typeof(SourceClass))]")
            .WithProperty<int>("Id")
            .WithProperty<string>("Name", propertyType: PropertyType.InitProperty | PropertyType.AutoProperty);

        var generatedFile = builder.AddFile(ExpectedFileName, autoGenerated: true);
        generatedFile.AddClass(SimpleExpectedExtensionClassThatMapsIdAndNameProperties(builder));

        return builder;
    }

    public static ITestSourceBuilder BuildEmployeeManagerModels(LanguageVersion version = LanguageVersion.CSharp10, ReferenceHandling referenceHandling = ReferenceHandling.Disabled)
    {
        var globalUsings = new[] { "System.Collections.Generic" };
        var builder = new TestSourceBuilder(TestSourceBuilderOptions.Create(version));
        var employeeFile = builder.AddFile("Employee", usings: globalUsings);

        employeeFile.AddClass("""
                              public class Employee
                              {
                                  private Manager _manager;
                              
                                  public int Id { get; set; }
                              
                                  public string EmployeeCode { get; set; }
                              
                                  public Manager Manager
                                  {
                                      get => _manager;
                                      set
                                      {
                                          if (value == null)
                                          {
                                              _manager.Employees.Remove(this);
                                          }
                                          else
                                          {
                                              value.Employees.Add(this);
                                          }
                              
                                          _manager = value;
                                      }
                                  }
                              }
                              """);

        var managerFile = builder.AddFile("Manager", usings: globalUsings);
        managerFile.AddClass("""
                             public class Manager : Employee
                             {
                                 public int Level { get; set; }
                             
                                 public List<Employee> Employees { get; set; } = new();
                             }
                             """);

        var employeeViewModelFile = builder.AddFile("EmployeeViewModel");
        employeeViewModelFile.AddClass($$"""
                                         [MapFrom(typeof(Employee), ReferenceHandling = MapTo.Configuration.ReferenceHandling.{{referenceHandling}})]
                                         public partial class EmployeeViewModel
                                         {
                                             public int Id { get; init; }
                                         
                                             public string EmployeeCode { get; set; }
                                         
                                             public ManagerViewModel Manager { get; set; }
                                         }
                                         """);

        var managerViewModelFile = builder.AddFile("ManagerViewModel", usings: globalUsings);
        managerViewModelFile.AddClass($$"""
                                        [MapFrom(typeof(Manager), ReferenceHandling = MapTo.Configuration.ReferenceHandling.{{referenceHandling}})]
                                        public partial class ManagerViewModel : EmployeeViewModel
                                        {
                                            public ManagerViewModel(int id) => Id = id;
                                        
                                            public int Level { get; init; }
                                        
                                            public List<EmployeeViewModel> Employees { get; set;  } = new();
                                        }
                                        """);

        return builder;
    }

    public static ITestSourceBuilder BuildSpotifyModels(TestSourceBuilderOptions? options = null) => new TestSourceBuilder(options ?? TestSourceBuilderOptions.Create())
        .AddExternalFile(Path.Combine(TestDataRelativeFolder, "SpotifyAlbum.cs"))
        .AddExternalFile(Path.Combine(TestDataRelativeFolder, "SpotifyAlbumDto.cs"));

    public static ITestSourceBuilder BuildAlbumAndArtistModels(TestSourceBuilderOptions? options = null)
    {
        var builder = new TestSourceBuilder(options ?? TestSourceBuilderOptions.Create());
        var sourceFile = builder.AddFile("Models");
        sourceFile.AddClass(
            """
            public class ExternalUrls
            {
                public string Url { get; set; }
            }
            """);

        sourceFile.AddClass(
            """
            public class Artist
            {
                public ExternalUrls ExternalUrls { get; set; }
            
                public int Id { get; set; }
            
                public string Name { get; set; } = string.Empty;
            }
            """);

        sourceFile.AddClass(
            """
            public class Album
            {
                public string Name { get; set; } = string.Empty;
            
                public Artist[] Artists { get; set; }
            }
            """);

        var viewModels = builder.AddFile("ViewModels");
        viewModels.AddClass(
            """
            [MapFrom(typeof(ExternalUrls))]
            public partial class ExternalUrlViewModel
            {
                public string Url { get; set; }
            }
            """);

        viewModels.AddClass(
            """
            [MapFrom(typeof(Artist))]
            public partial class ArtistViewModel
            {
                public ExternalUrlViewModel ExternalUrls { get; set; }
            
                public int Id { get; set; }
            
                public string Name { get; set; } = string.Empty;
            }
            """);

        viewModels.AddClass(
            """
            [MapFrom(typeof(Album))]
            public partial class AlbumViewModel
            {
                public string Name { get; set; } = string.Empty;
            
                public ArtistViewModel[] Artists { get; set; }
            }
            """);

        return builder;
    }

    private static string SimpleExpectedExtensionClassThatMapsIdAndNameProperties(ITestSourceBuilder builder) => builder.Options.SupportNullReferenceTypes
        ? $$"""
            {{GeneratedCodeAttribute}}
            public static class SourceClassMapToExtensions
            {
                [return: {{NotNullIfNotNull}}("sourceClass")]
                public static TargetClass? MapToTargetClass(this SourceClass? sourceClass)
                {
                    if (ReferenceEquals(sourceClass, null))
                    {
                        return null;
                    }
            
                    return new TargetClass
                    {
                        Id = sourceClass.Id,
                        Name = sourceClass.Name
                    };
                }
            }
            """
        : $$"""
            {{GeneratedCodeAttribute}}
            public static class SourceClassMapToExtensions
            {
                [return: {{NotNullIfNotNull}}("sourceClass")]
                public static TargetClass MapToTargetClass([{{AllowNull}}] this SourceClass sourceClass)
                {
                    if (ReferenceEquals(sourceClass, null))
                    {
                        return null;
                    }
            
                    return new TargetClass
                    {
                        Id = sourceClass.Id,
                        Name = sourceClass.Name
                    };
                }
            }
            """;
}