using MapTo.Mappings;

namespace MapTo.Generators;

internal readonly record struct FileGenerator(
    bool SupportNullReferenceTypes,
    bool SupportFileScopedNamespace,
    TargetMapping Mapping) : ICodeBlockGenerator
{
    /// <inheritdoc />
    public void BeginWrite(CodeWriter writer)
    {
        writer
            .WriteAutoGeneratedHeader()
            .WriteNullableContextOptionIf(SupportNullReferenceTypes);

        if (SupportFileScopedNamespace)
        {
            writer.WriteLine($"namespace {Mapping.Namespace};");
            writer.WriteLine();
        }
        else
        {
            writer.WriteLine($"namespace {Mapping.Namespace}");
            writer.WriteOpeningBracket();
        }

        writer.WriteUsings(Mapping.UsingDirectives);
    }

    /// <inheritdoc />
    public void EndWrite(CodeWriter writer)
    {
        writer.WriteClosingBracketIf(!SupportFileScopedNamespace);
    }
}