// <auto-generated />

namespace MapTo
{
    using System;

    /// <summary>
    /// Specifies the source type to map from.
    /// </summary>
    [AttributeUsage(AttributeTargets.Property, Inherited = false, AllowMultiple = false)]
    public sealed class IgnorePropertyAttribute : Attribute
    {
    }
}