// <auto-generated />

namespace MapTo
{
    using System;
    
    /// <summary>
    /// Specifies that annotated constructor should be used for mapping objects.
    /// </summary>
    [AttributeUsage(AttributeTargets.Constructor, AllowMultiple = false)]
    public sealed class MapConstructorAttribute : Attribute
    {
    }
}