// <auto-generated />

#if NETSTANDARD2_1_OR_GREATER
#nullable enable
#endif

namespace MapTo
{
    using System;

    /// <summary>
    /// Specifies that a property should be mapped to a source property.
    /// </summary>
    [AttributeUsage(AttributeTargets.Property | AttributeTargets.Parameter, AllowMultiple = true)]
    public sealed class MapPropertyAttribute : Attribute
    {
        /// <summary>
        /// Gets or sets the name of the source property to map to.
        /// </summary>
        /// <value>The name of the source property to map to.</value>
#if NETSTANDARD2_1_OR_GREATER
        public string? SourcePropertyName { get; set; }
#else
        public string SourcePropertyName { get; set; }
#endif
    }
}